export const GLOBALTYPES = {
  AUTH: "AUTH",
  ALERT: "ALERT",

  // Unit
  GET_ALL_UNIT: 'GET_ALL_UNIT',
  CREATE_UNIT: 'CREATE_UNIT',
  UPDATE_UNIT: 'UPDATE_UNIT',

  // User
  GET_CHILD_USER: 'GET_CHILD_USER',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER_BY_ID: 'UPDATE_USER_BY_ID',
  DELETE_USER_BY_ID: 'DELETE_USER_BY_ID', 
};
